### ISSUE TITLE
Unable to publish content after upgrade to episerver 10 with ImageDataExtensions installed

### ISSUE THREAD

**Issue by baktakt** [markeverard/Chief2moro.ImageDataExtensions#4]
Episerver has made some breaking changes when going from version 9 to 10. Quite a lot of implementations have been moved to internal namespaces. This file for example uses the ThumbnailManager, which is one of the implementations moved to an internal namespace:
https://github.com/markeverard/Chief2moro.ImageDataExtensions/blob/4c6b23a43faab5ac2eab9c4f680beb138af65204/src/Chief2moro.ImageDataExtensions/ImageResizeContentEvents.cs

With the plugin installed you can no longer publish content in edit mode since it throws an error about not finding EPiServer.Core.ThumbnailManager since it is now found in EPiServer.Core.Internal.

**Comment by markeverard** [comment]
@LucGosso submitted a pull request that upgrades the package to Epi 10. This will be available on the Epi nuget feed within the next day or so. It is still use at own risk purely because of the dependancy on the unsupported / internal ThumbnailManager class
